# Generated by Django 4.2.7 on 2025-06-02 02:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cccd",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", "CCCD phải có đúng 12 chữ số"
                            )
                        ],
                        verbose_name="Số CCCD",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Họ tên")),
                ("birth_date", models.DateField(verbose_name="Ngày sinh")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Nam"), ("F", "Nữ")],
                        max_length=1,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mã nhân viên"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Chức vụ"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Phòng ban"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày vào làm"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                        verbose_name="Công ty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Nhân viên",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Tên sản phẩm"),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mã sản phẩm"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Ngày mua")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Số lượng"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Tổng tiền"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Số đơn hàng"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="employees.employee",
                        verbose_name="Nhân viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử mua hàng",
                "verbose_name_plural": "Lịch sử mua hàng",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("lookup", "Tra cứu"),
                            ("create", "Tạo mới"),
                            ("update", "Cập nhật"),
                            ("delete", "Xóa"),
                        ],
                        max_length=20,
                        verbose_name="Hành động",
                    ),
                ),
                (
                    "target_cccd",
                    models.CharField(max_length=12, verbose_name="CCCD được tra cứu"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Địa chỉ IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Chi tiết"),
                ),
                (
                    "target_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Nhân viên",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký hệ thống",
                "verbose_name_plural": "Nhật ký hệ thống",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["cccd"], name="employees_e_cccd_09b127_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "is_active"], name="employees_e_company_44de86_idx"
            ),
        ),
    ]
