# Generated by Django 4.2.7 on 2025-06-02 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LDAPUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Username LDAP"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin_corporation", "Admin Tập đoàn"),
                            ("admin_company", "Admin Công ty"),
                            ("manager", "Nhân viên quản lý"),
                        ],
                        max_length=20,
                        verbose_name="Vai trò",
                    ),
                ),
                (
                    "is_allowed",
                    models.BooleanField(
                        default=True, verbose_name="Được phép truy cập"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                        verbose_name="Công ty",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Được tạo bởi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quyền LDAP User",
                "verbose_name_plural": "Quyền LDAP Users",
            },
        ),
    ]
