# Generated by Django 4.2.7 on 2025-06-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên công ty")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã công ty"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Công ty",
                "verbose_name_plural": "Công ty",
                "ordering": ["name"],
            },
        ),
    ]
